classDiagram
    class Main
    class Configuracao
    class Carga
    class Simulador {
        -long clock
        -PriorityQueue eventos
        +simular()
        +agendar()
        +bloquear()
        +tornarPronta()
    }
    class Evento {
        instante
        ordemTipo
        sequencia
        acao
    }
    class Processo {
        PCB
        id
        prioridade
        chegada
        tabelaPaginas
        arquivosAbertos
        atualizarEstado()
    }
    class ThreadSimulada {
        TCB
        contadorPrograma
        acumulador
        pilha
        caixaEntrada
        mudarEstado()
    }
    class Estado
    class Instrucao
    class Escalonador {
        Politica
        prontos
        adicionar()
        retirar()
    }
    class Memoria {
        molduras
        ordemFifo
        pendentes
        acessar()
        liberar()
    }
    class Dispositivo {
        nome
        fila
        tempoServico
        solicitar()
    }
    class Arquivos {
        raiz
        blocos
        tabelaGlobal
        criar()
        abrir()
        ler()
        escrever()
        fechar()
        remover()
        listar()
    }
    class Metricas
    Main ..> Configuracao
    Main ..> Carga
    Main ..> Simulador
    Carga ..> Processo
    Simulador *-- Evento
    Simulador o-- Processo
    Processo *-- ThreadSimulada
    Processo --> Estado
    ThreadSimulada --> Estado
    ThreadSimulada *-- Instrucao
    Simulador *-- Escalonador
    Simulador *-- Memoria
    Simulador *-- Dispositivo
    Simulador *-- Arquivos
    Simulador ..> Metricas
    Escalonador o-- ThreadSimulada
    Memoria --> Processo
    Dispositivo --> ThreadSimulada
    Arquivos --> Processo

    class InterfaceGrafica
    class LinhaTempo
    InterfaceGrafica ..> Main : executar
    InterfaceGrafica *-- LinhaTempo
    InterfaceGrafica ..> Metricas

    class TemaAero
    class PainelDoom
    class Doom
    InterfaceGrafica ..> TemaAero
    InterfaceGrafica *-- PainelDoom
    PainelDoom *-- Doom
